2022-12-02 16:32:52,495 [INFO] A new session has been established (session id: 13d890c1-4496-449d-a867-2e05d06746fe)
2022-12-02 16:32:52,495 [INFO] ⚡️ Bolt app is running!
2022-12-02 16:32:52,578 [INFO] Starting to receive messages from a new connection (session id: 13d890c1-4496-449d-a867-2e05d06746fe)
2022-12-02 16:33:03,634 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'files')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 28, in upload_file
    gdrive_update_upload(folder_id="1X3Qew8QlzOWwhtFjYOBtfMqaVnvEzRye")
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/utils/googledrive_api/gdrive_update_upload.py", line 30, in gdrive_update_upload
    for file in os.listdir("files")
FileNotFoundError: [Errno 2] No such file or directory: 'files'
2022-12-02 16:33:05,336 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'files')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 28, in upload_file
    gdrive_update_upload(folder_id="1X3Qew8QlzOWwhtFjYOBtfMqaVnvEzRye")
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/utils/googledrive_api/gdrive_update_upload.py", line 30, in gdrive_update_upload
    for file in os.listdir("files")
FileNotFoundError: [Errno 2] No such file or directory: 'files'
2022-12-02 16:36:19,875 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'files')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 28, in upload_file
    def upload_file(self, channel):
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/utils/googledrive_api/gdrive_update_upload.py", line 30, in gdrive_update_upload
    os.path.join("files", file).split("/")[-1]: os.path.join("files", file)
FileNotFoundError: [Errno 2] No such file or directory: 'files'
2022-12-02 16:36:32,067 [INFO] A new session has been established (session id: 1deeb0cc-3142-423e-9d37-b61c421bab0b)
2022-12-02 16:36:32,067 [INFO] ⚡️ Bolt app is running!
2022-12-02 16:36:32,094 [INFO] Starting to receive messages from a new connection (session id: 1deeb0cc-3142-423e-9d37-b61c421bab0b)
2022-12-02 16:36:42,382 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'slackbot/utils/googledrive_api')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 29, in upload_file
    os.chdir("slackbot/utils/googledrive_api")
FileNotFoundError: [Errno 2] No such file or directory: 'slackbot/utils/googledrive_api'
2022-12-02 16:36:44,207 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'slackbot/utils/googledrive_api')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 29, in upload_file
    os.chdir("slackbot/utils/googledrive_api")
FileNotFoundError: [Errno 2] No such file or directory: 'slackbot/utils/googledrive_api'
2022-12-02 16:37:16,484 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'slackbot/utils/googledrive_api')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 29, in upload_file
    os.chdir("../utils/googledrive_api")
FileNotFoundError: [Errno 2] No such file or directory: 'slackbot/utils/googledrive_api'
2022-12-02 16:37:32,675 [INFO] A new session has been established (session id: 361c87cb-051c-4cb0-b52e-1d29b6736cd7)
2022-12-02 16:37:32,675 [INFO] ⚡️ Bolt app is running!
2022-12-02 16:37:32,697 [INFO] Starting to receive messages from a new connection (session id: 361c87cb-051c-4cb0-b52e-1d29b6736cd7)
2022-12-02 16:37:34,264 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../utils/googledrive_api')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 29, in upload_file
    os.chdir("../utils/googledrive_api")
FileNotFoundError: [Errno 2] No such file or directory: '../utils/googledrive_api'
2022-12-02 16:38:16,725 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../utils/googledrive_api')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 29, in upload_file
    # os.chdir("../utils/googledrive_api")
FileNotFoundError: [Errno 2] No such file or directory: '../utils/googledrive_api'
2022-12-02 16:38:17,956 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../utils/googledrive_api')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 29, in upload_file
    # os.chdir("../utils/googledrive_api")
FileNotFoundError: [Errno 2] No such file or directory: '../utils/googledrive_api'
2022-12-02 16:38:35,661 [INFO] A new session has been established (session id: bbde4bb9-1936-4c33-bca6-7d903e120bc4)
2022-12-02 16:38:35,662 [INFO] ⚡️ Bolt app is running!
2022-12-02 16:38:35,738 [INFO] Starting to receive messages from a new connection (session id: bbde4bb9-1936-4c33-bca6-7d903e120bc4)
2022-12-02 16:38:41,156 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'files')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 31, in upload_file
    gdrive_update_upload(folder_id="1X3Qew8QlzOWwhtFjYOBtfMqaVnvEzRye")
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/utils/googledrive_api/gdrive_update_upload.py", line 31, in gdrive_update_upload
    for file in os.listdir("files")
FileNotFoundError: [Errno 2] No such file or directory: 'files'
2022-12-02 16:39:39,909 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'files')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 31, in upload_file
    gdrive_update_upload(folder_id="1X3Qew8QlzOWwhtFjYOBtfMqaVnvEzRye")
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/utils/googledrive_api/gdrive_update_upload.py", line 31, in gdrive_update_upload
    for file in os.listdir("files")
FileNotFoundError: [Errno 2] No such file or directory: 'files'
2022-12-02 16:40:06,576 [INFO] A new session has been established (session id: b62d167f-5e95-4032-900d-699cbca59770)
2022-12-02 16:40:06,585 [INFO] ⚡️ Bolt app is running!
2022-12-02 16:40:06,643 [INFO] Starting to receive messages from a new connection (session id: b62d167f-5e95-4032-900d-699cbca59770)
2022-12-02 16:40:10,629 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '/utils')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 29, in upload_file
    os.chdir("/utils")
FileNotFoundError: [Errno 2] No such file or directory: '/utils'
2022-12-02 16:40:45,036 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '/utils')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 29, in upload_file
    os.chdir("utils/")
FileNotFoundError: [Errno 2] No such file or directory: '/utils'
2022-12-02 16:40:46,732 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '/utils')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 29, in upload_file
    os.chdir("utils/")
FileNotFoundError: [Errno 2] No such file or directory: '/utils'
2022-12-02 16:41:12,822 [INFO] A new session has been established (session id: 4e306bd7-97a0-433a-8ee2-fe94d9f78dfa)
2022-12-02 16:41:12,825 [INFO] ⚡️ Bolt app is running!
2022-12-02 16:41:12,867 [INFO] Starting to receive messages from a new connection (session id: 4e306bd7-97a0-433a-8ee2-fe94d9f78dfa)
2022-12-02 16:41:16,828 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'utils/')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 29, in upload_file
    os.chdir("utils/")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/'
2022-12-02 16:42:52,777 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'utils/')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 29, in upload_file
    print(os.getcwd())
FileNotFoundError: [Errno 2] No such file or directory: 'utils/'
2022-12-02 16:43:21,922 [INFO] A new session has been established (session id: 27260256-98bb-4662-8f07-7364bf653649)
2022-12-02 16:43:21,923 [INFO] ⚡️ Bolt app is running!
2022-12-02 16:43:21,996 [INFO] Starting to receive messages from a new connection (session id: 27260256-98bb-4662-8f07-7364bf653649)
2022-12-02 16:43:25,198 [INFO] Files to be updated/uploaded: dict_keys(['test.png'])...
2022-12-02 16:43:25,203 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 16:43:25,857 [INFO] test.png file located in google drive...
2022-12-02 16:43:25,889 [INFO] Updating test.png file contents...
2022-12-02 16:43:29,059 [INFO] File successfully updated!
2022-12-02 16:44:38,367 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'utils/googledrive_api')
Traceback (most recent call last):
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/cfiore/Documents/GitHub/project_conduit/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/cfiore/Documents/GitHub/project_conduit/slackbot/buttons/file_upload_button.py", line 30, in upload_file
    os.chdir("utils/googledrive_api")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/googledrive_api'
2022-12-02 16:46:10,519 [INFO] A new session has been established (session id: 22f99211-8c80-413e-bd72-ce73a07543b7)
2022-12-02 16:46:10,519 [INFO] ⚡️ Bolt app is running!
2022-12-02 16:46:10,570 [INFO] Starting to receive messages from a new connection (session id: 22f99211-8c80-413e-bd72-ce73a07543b7)
2022-12-02 16:46:15,530 [INFO] Files to be updated/uploaded: dict_keys(['test.png'])...
2022-12-02 16:46:15,535 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 16:46:16,105 [INFO] test.png file located in google drive...
2022-12-02 16:46:16,135 [INFO] Updating test.png file contents...
2022-12-02 16:46:18,910 [INFO] File successfully updated!
2022-12-02 17:01:48,216 [INFO] A new session has been established (session id: bc4b4353-13fa-4a02-9666-bfc7c1b1feb6)
2022-12-02 17:01:48,216 [INFO] ⚡️ Bolt app is running!
2022-12-02 17:01:48,255 [INFO] Starting to receive messages from a new connection (session id: bc4b4353-13fa-4a02-9666-bfc7c1b1feb6)
2022-12-02 17:02:26,689 [INFO] Files to be updated/uploaded: dict_keys(['test.png'])...
2022-12-02 17:02:26,689 [ERROR] Failed to run listener function (error: local variable 'drive' referenced before assignment)
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 32, in upload_file
    gdrive_update_upload(folder_id="1X3Qew8QlzOWwhtFjYOBtfMqaVnvEzRye")
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/googledrive_api/gdrive_update_upload.py", line 35, in gdrive_update_upload
    gfiles = drive.ListFile(
UnboundLocalError: local variable 'drive' referenced before assignment
2022-12-02 17:13:58,160 [INFO] A new session has been established (session id: 80ed1040-f6ef-4511-a87f-41a78679f727)
2022-12-02 17:13:58,160 [INFO] ⚡️ Bolt app is running!
2022-12-02 17:13:58,167 [INFO] Starting to receive messages from a new connection (session id: 80ed1040-f6ef-4511-a87f-41a78679f727)
2022-12-02 17:14:08,638 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 17:14:08,638 [INFO] Successfully retrieved access token
2022-12-02 17:14:08,640 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 17:14:08,642 [INFO] Files to be updated/uploaded: dict_keys(['test.png'])...
2022-12-02 17:14:09,111 [INFO] test.png file located in google drive...
2022-12-02 17:14:09,130 [INFO] Updating test.png file contents...
2022-12-02 17:14:12,572 [INFO] File successfully updated!
2022-12-02 17:50:36,317 [INFO] A new session has been established (session id: a682056c-ba11-429f-a829-17848c63d041)
2022-12-02 17:50:36,317 [INFO] ⚡️ Bolt app is running!
2022-12-02 17:50:36,358 [INFO] Starting to receive messages from a new connection (session id: a682056c-ba11-429f-a829-17848c63d041)
2022-12-02 17:50:54,817 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 37, in upload_file
    os.chdir("../googledrive_api")
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api'
2022-12-02 17:52:35,667 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'utils/tableau_api')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 30, in upload_file
    os.chdir("utils/tableau_api")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/tableau_api'
2022-12-02 17:53:15,193 [INFO] A new session has been established (session id: 4366ca88-ea8f-4d4d-99f2-a89d8d047383)
2022-12-02 17:53:15,193 [INFO] ⚡️ Bolt app is running!
2022-12-02 17:53:15,241 [INFO] Starting to receive messages from a new connection (session id: 4366ca88-ea8f-4d4d-99f2-a89d8d047383)
2022-12-02 17:53:22,353 [ERROR] Failed to run listener function (error: chdir() missing required argument 'path' (pos 1))
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 36, in upload_file
    print(os.chdir())
TypeError: chdir() missing required argument 'path' (pos 1)
2022-12-02 17:53:47,797 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'utils/tableau_api')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 30, in upload_file
    os.chdir("utils/tableau_api")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/tableau_api'
2022-12-02 17:54:02,664 [INFO] A new session has been established (session id: 3bc9881a-e619-4524-86fb-38bbf1cdd20a)
2022-12-02 17:54:02,665 [INFO] ⚡️ Bolt app is running!
2022-12-02 17:54:02,670 [INFO] Starting to receive messages from a new connection (session id: 3bc9881a-e619-4524-86fb-38bbf1cdd20a)
2022-12-02 17:54:08,684 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 38, in upload_file
    os.chdir("../googledrive_api")
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api'
2022-12-02 17:54:54,075 [INFO] A new session has been established (session id: 3f5b6e02-f579-4d21-aaa1-903b20250fa8)
2022-12-02 17:54:54,075 [INFO] ⚡️ Bolt app is running!
2022-12-02 17:54:54,087 [INFO] Starting to receive messages from a new connection (session id: 3f5b6e02-f579-4d21-aaa1-903b20250fa8)
2022-12-02 17:55:09,742 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 38, in upload_file
    os.chdir("../googledrive_api")
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api'
2022-12-02 17:55:54,133 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'utils/tableau_api')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 30, in upload_file
    os.chdir("utils/tableau_api")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/tableau_api'
2022-12-02 17:56:51,901 [INFO] A new session has been established (session id: b0ad8a98-480e-46bb-901e-64b547a2dc8c)
2022-12-02 17:56:51,901 [INFO] ⚡️ Bolt app is running!
2022-12-02 17:56:51,908 [INFO] Starting to receive messages from a new connection (session id: b0ad8a98-480e-46bb-901e-64b547a2dc8c)
2022-12-02 17:57:13,525 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 17:57:13,525 [INFO] Successfully retrieved access token
2022-12-02 17:57:13,539 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 17:57:13,545 [INFO] Files to be updated/uploaded: dict_keys(['test.png', 'default.pdf'])...
2022-12-02 17:57:14,093 [INFO] test.png file located in google drive...
2022-12-02 17:57:14,098 [INFO] Updating test.png file contents...
2022-12-02 17:57:17,668 [INFO] File successfully updated!
2022-12-02 17:57:17,669 [INFO] default.pdf file not located in google drive...
2022-12-02 17:57:17,669 [INFO] Uploading default.pdf file contents...
2022-12-02 17:57:19,477 [INFO] File successfully uploaded!
2022-12-02 17:59:12,659 [INFO] A new session has been established (session id: e3063e41-901b-48d7-8a35-37452ef6eed6)
2022-12-02 17:59:12,660 [INFO] ⚡️ Bolt app is running!
2022-12-02 17:59:12,690 [INFO] Starting to receive messages from a new connection (session id: e3063e41-901b-48d7-8a35-37452ef6eed6)
2022-12-02 17:59:21,788 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'files')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 40, in upload_file
    gdrive_update_upload(folder_id="1X3Qew8QlzOWwhtFjYOBtfMqaVnvEzRye")
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/googledrive_api/gdrive_update_upload.py", line 32, in gdrive_update_upload
    for file in os.listdir("files")
FileNotFoundError: [Errno 2] No such file or directory: 'files'
2022-12-02 18:04:02,160 [INFO] A new session has been established (session id: 70eb4042-73cd-48f6-9c6f-bb6737252713)
2022-12-02 18:04:02,160 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:04:02,161 [INFO] Starting to receive messages from a new connection (session id: 70eb4042-73cd-48f6-9c6f-bb6737252713)
2022-12-02 18:04:08,964 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files/default.pdf')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 34, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', None)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 56, in generate_pdf
    with open(file_path, 'wb') as pdf_file:
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files/default.pdf'
2022-12-02 18:08:55,183 [INFO] A new session has been established (session id: f0341efc-09e5-4338-b7bd-f2b4175a18f9)
2022-12-02 18:08:55,184 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:08:55,206 [INFO] Starting to receive messages from a new connection (session id: f0341efc-09e5-4338-b7bd-f2b4175a18f9)
2022-12-02 18:09:16,449 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files/default.pdf')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 34, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', None)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 56, in generate_pdf
    with open(file_path, 'wb') as pdf_file:
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files/default.pdf'
2022-12-02 18:11:01,082 [INFO] A new session has been established (session id: 3f5203da-4b5c-4977-98e1-d67babcacebd)
2022-12-02 18:11:01,082 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:11:01,170 [INFO] Starting to receive messages from a new connection (session id: 3f5203da-4b5c-4977-98e1-d67babcacebd)
2022-12-02 18:11:14,165 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 38, in upload_file
    os.chdir("../googledrive_api")
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api'
2022-12-02 18:11:34,217 [INFO] A new session has been established (session id: a8e7dcd2-e929-4a68-b56c-4b60b8e268a5)
2022-12-02 18:11:34,218 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:11:34,235 [INFO] Starting to receive messages from a new connection (session id: a8e7dcd2-e929-4a68-b56c-4b60b8e268a5)
2022-12-02 18:11:42,971 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 18:11:42,972 [INFO] Successfully retrieved access token
2022-12-02 18:11:42,985 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:11:42,992 [INFO] Files to be updated/uploaded: dict_keys(['test.png', 'default.pdf'])...
2022-12-02 18:11:43,673 [INFO] test.png file located in google drive...
2022-12-02 18:11:43,682 [INFO] Updating test.png file contents...
2022-12-02 18:11:47,355 [INFO] File successfully updated!
2022-12-02 18:11:47,356 [INFO] default.pdf file located in google drive...
2022-12-02 18:11:47,356 [INFO] Updating default.pdf file contents...
2022-12-02 18:11:49,390 [INFO] File successfully updated!
2022-12-02 18:11:49,391 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: b'files/default.pdf')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 43, in upload_file
    self.app.client.files_upload(channels=channel, file=self.file_path)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/client.py", line 2990, in files_upload
    return self.api_call("files.upload", files={"file": file}, data=kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 269, in _urllib_api_call
    f: BinaryIO = open(v.encode("utf-8", "ignore"), "rb")
FileNotFoundError: [Errno 2] No such file or directory: b'files/default.pdf'
2022-12-02 18:12:42,724 [INFO] A new session has been established (session id: f5ebbb05-9757-4530-a7c4-fc08d78be5fb)
2022-12-02 18:12:42,724 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:12:42,731 [INFO] Starting to receive messages from a new connection (session id: f5ebbb05-9757-4530-a7c4-fc08d78be5fb)
2022-12-02 18:12:51,873 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 18:12:51,874 [INFO] Successfully retrieved access token
2022-12-02 18:12:51,880 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:12:51,888 [INFO] Files to be updated/uploaded: dict_keys(['test.png', 'default.pdf'])...
2022-12-02 18:12:52,481 [INFO] test.png file located in google drive...
2022-12-02 18:12:52,491 [INFO] Updating test.png file contents...
2022-12-02 18:12:56,582 [INFO] File successfully updated!
2022-12-02 18:12:56,582 [INFO] default.pdf file located in google drive...
2022-12-02 18:12:56,583 [INFO] Updating default.pdf file contents...
2022-12-02 18:12:58,642 [INFO] File successfully updated!
2022-12-02 18:12:58,644 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: b'files/default.pdf')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 43, in upload_file
    self.app.client.files_upload(channels=channel, file=self.file_path)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/client.py", line 2990, in files_upload
    return self.api_call("files.upload", files={"file": file}, data=kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 269, in _urllib_api_call
    f: BinaryIO = open(v.encode("utf-8", "ignore"), "rb")
FileNotFoundError: [Errno 2] No such file or directory: b'files/default.pdf'
2022-12-02 18:14:15,762 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 36, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', None)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 54, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 18:14:34,331 [INFO] A new session has been established (session id: 4f4a0167-69f4-4625-aeeb-1f5e7882424b)
2022-12-02 18:14:34,331 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:14:34,333 [INFO] Starting to receive messages from a new connection (session id: 4f4a0167-69f4-4625-aeeb-1f5e7882424b)
2022-12-02 18:14:41,994 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 36, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', None)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 54, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 18:15:55,109 [INFO] A new session has been established (session id: eabbfcc9-bb32-4f02-b35d-96072adb5c9d)
2022-12-02 18:15:55,109 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:15:55,130 [INFO] Starting to receive messages from a new connection (session id: eabbfcc9-bb32-4f02-b35d-96072adb5c9d)
2022-12-02 18:16:01,563 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 36, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', None)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 56, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 18:16:20,102 [INFO] A new session has been established (session id: 8c5b0f9a-e78f-4b6e-8bf7-b9a04dd37430)
2022-12-02 18:16:20,102 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:16:20,154 [INFO] Starting to receive messages from a new connection (session id: 8c5b0f9a-e78f-4b6e-8bf7-b9a04dd37430)
2022-12-02 18:16:25,866 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'utils/tableau_api')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 32, in upload_file
    os.chdir("utils/tableau_api")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/tableau_api'
2022-12-02 18:16:28,201 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 36, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', None)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 56, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 18:16:45,589 [INFO] A new session has been established (session id: a3a8c2de-5981-4c36-b798-f61abc6119f8)
2022-12-02 18:16:45,589 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:16:45,671 [INFO] Starting to receive messages from a new connection (session id: a3a8c2de-5981-4c36-b798-f61abc6119f8)
2022-12-02 18:16:55,159 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 36, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', None)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 56, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 18:18:44,089 [INFO] A new session has been established (session id: f766949f-f27e-4dd8-bf3f-7ec5e6a44261)
2022-12-02 18:18:44,089 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:18:44,100 [INFO] Starting to receive messages from a new connection (session id: f766949f-f27e-4dd8-bf3f-7ec5e6a44261)
2022-12-02 18:18:55,457 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 18:18:55,458 [INFO] Successfully retrieved access token
2022-12-02 18:18:55,471 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:18:55,477 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:18:55,972 [INFO] default.pdf file located in google drive...
2022-12-02 18:18:55,983 [INFO] Updating default.pdf file contents...
2022-12-02 18:18:58,000 [INFO] File successfully updated!
2022-12-02 18:18:58,002 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: b'files/default.pdf')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 43, in upload_file
    self.app.client.files_upload(channels=channel, file=self.file_path)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/client.py", line 2990, in files_upload
    return self.api_call("files.upload", files={"file": file}, data=kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 269, in _urllib_api_call
    f: BinaryIO = open(v.encode("utf-8", "ignore"), "rb")
FileNotFoundError: [Errno 2] No such file or directory: b'files/default.pdf'
2022-12-02 18:21:04,951 [INFO] A new session has been established (session id: deba5166-1feb-4130-aadd-c7a02d63bf6c)
2022-12-02 18:21:04,952 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:21:04,958 [INFO] Starting to receive messages from a new connection (session id: deba5166-1feb-4130-aadd-c7a02d63bf6c)
2022-12-02 18:21:18,440 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 18:21:18,442 [INFO] Successfully retrieved access token
2022-12-02 18:21:18,452 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:21:18,457 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:21:18,928 [INFO] default.pdf file located in google drive...
2022-12-02 18:21:18,939 [INFO] Updating default.pdf file contents...
2022-12-02 18:21:20,918 [INFO] File successfully updated!
2022-12-02 18:21:20,919 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: b'files/default.pdf')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 43, in upload_file
    self.app.client.files_upload(channels=channel, file=self.file_path)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/client.py", line 2990, in files_upload
    return self.api_call("files.upload", files={"file": file}, data=kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 269, in _urllib_api_call
    f: BinaryIO = open(v.encode("utf-8", "ignore"), "rb")
FileNotFoundError: [Errno 2] No such file or directory: b'files/default.pdf'
2022-12-02 18:22:14,243 [INFO] A new session has been established (session id: fabf2f8e-ac94-4c60-a486-a8c4ac17fdf0)
2022-12-02 18:22:14,243 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:22:14,298 [INFO] Starting to receive messages from a new connection (session id: fabf2f8e-ac94-4c60-a486-a8c4ac17fdf0)
2022-12-02 18:23:14,129 [INFO] A new session has been established (session id: c8dc26dc-3123-40f0-b2f9-680681c13f71)
2022-12-02 18:23:14,129 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:23:14,170 [INFO] Starting to receive messages from a new connection (session id: c8dc26dc-3123-40f0-b2f9-680681c13f71)
2022-12-02 18:23:29,958 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 39, in upload_file
    os.chdir("../googledrive_api/files")
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 18:24:30,550 [INFO] A new session has been established (session id: eff67bca-682f-49fa-bea6-b5cded29d5bb)
2022-12-02 18:24:30,550 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:24:30,556 [INFO] Starting to receive messages from a new connection (session id: eff67bca-682f-49fa-bea6-b5cded29d5bb)
2022-12-02 18:24:41,608 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 40, in upload_file
    os.chdir("../googledrive_api")
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api'
2022-12-02 18:26:07,763 [INFO] A new session has been established (session id: ccace1d6-fb1e-451c-b788-f8bf1813eda2)
2022-12-02 18:26:07,763 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:26:07,777 [INFO] Starting to receive messages from a new connection (session id: ccace1d6-fb1e-451c-b788-f8bf1813eda2)
2022-12-02 18:26:09,401 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'utils/tableau_api')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 32, in upload_file
    os.chdir("utils/tableau_api")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/tableau_api'
2022-12-02 18:26:19,444 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 18:26:19,445 [INFO] Successfully retrieved access token
2022-12-02 18:26:19,457 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:26:19,463 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:26:20,027 [INFO] default.pdf file located in google drive...
2022-12-02 18:26:20,033 [INFO] Updating default.pdf file contents...
2022-12-02 18:26:22,123 [INFO] File successfully updated!
2022-12-02 18:26:40,533 [INFO] A new session has been established (session id: c035a7e3-49f2-4116-acf7-4a78df15a739)
2022-12-02 18:26:40,533 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:26:40,600 [INFO] Starting to receive messages from a new connection (session id: c035a7e3-49f2-4116-acf7-4a78df15a739)
2022-12-02 18:26:57,914 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 18:26:57,914 [INFO] Successfully retrieved access token
2022-12-02 18:26:57,927 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:26:57,929 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:26:58,434 [INFO] default.pdf file located in google drive...
2022-12-02 18:26:58,441 [INFO] Updating default.pdf file contents...
2022-12-02 18:27:00,381 [INFO] File successfully updated!
2022-12-02 18:27:15,175 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'utils/tableau_api')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 32, in upload_file
    os.chdir("utils/tableau_api")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/tableau_api'
2022-12-02 18:27:55,779 [INFO] A new session has been established (session id: dbda62f4-a0c0-4768-bcb5-a949c0b1fd16)
2022-12-02 18:27:55,779 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:27:55,815 [INFO] Starting to receive messages from a new connection (session id: dbda62f4-a0c0-4768-bcb5-a949c0b1fd16)
2022-12-02 18:28:10,366 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 18:28:10,367 [INFO] Successfully retrieved access token
2022-12-02 18:28:10,376 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:28:10,383 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:28:10,867 [INFO] default.pdf file located in google drive...
2022-12-02 18:28:10,880 [INFO] Updating default.pdf file contents...
2022-12-02 18:28:12,755 [INFO] File successfully updated!
2022-12-02 18:28:12,757 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: b'files/default.pdf')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 46, in upload_file
    self.app.client.files_upload(channels=channel, file=self.file_path)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/client.py", line 2990, in files_upload
    return self.api_call("files.upload", files={"file": file}, data=kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/opt/homebrew/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 269, in _urllib_api_call
    f: BinaryIO = open(v.encode("utf-8", "ignore"), "rb")
FileNotFoundError: [Errno 2] No such file or directory: b'files/default.pdf'
2022-12-02 18:28:48,468 [INFO] A new session has been established (session id: 4da4d918-9579-4a89-b0cf-913e0287c9eb)
2022-12-02 18:28:48,469 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:28:48,572 [INFO] Starting to receive messages from a new connection (session id: 4da4d918-9579-4a89-b0cf-913e0287c9eb)
2022-12-02 18:29:01,854 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 18:29:01,855 [INFO] Successfully retrieved access token
2022-12-02 18:29:01,869 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:29:01,875 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:29:02,362 [INFO] default.pdf file located in google drive...
2022-12-02 18:29:02,364 [INFO] Updating default.pdf file contents...
2022-12-02 18:29:04,308 [INFO] File successfully updated!
2022-12-02 18:29:17,793 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 18:29:17,793 [INFO] Successfully retrieved access token
2022-12-02 18:29:17,801 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:29:17,807 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:29:18,329 [INFO] default.pdf file located in google drive...
2022-12-02 18:29:18,329 [INFO] Updating default.pdf file contents...
2022-12-02 18:29:20,277 [INFO] File successfully updated!
2022-12-02 18:31:06,445 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'utils/tableau_api')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 33, in upload_file
    os.chdir("utils/tableau_api")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/tableau_api'
2022-12-02 18:31:11,527 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 18:31:11,527 [INFO] Successfully retrieved access token
2022-12-02 18:31:11,535 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:31:11,541 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:31:12,106 [INFO] default.pdf file located in google drive...
2022-12-02 18:31:12,106 [INFO] Updating default.pdf file contents...
2022-12-02 18:31:14,023 [INFO] File successfully updated!
2022-12-02 18:31:54,128 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 18:31:54,128 [INFO] Successfully retrieved access token
2022-12-02 18:31:54,138 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:31:54,144 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:31:54,732 [INFO] default.pdf file located in google drive...
2022-12-02 18:31:54,732 [INFO] Updating default.pdf file contents...
2022-12-02 18:31:54,978 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'utils/tableau_api')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 80, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 33, in upload_file
    os.chdir("utils/tableau_api")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/tableau_api'
2022-12-02 18:31:56,672 [INFO] File successfully updated!
2022-12-02 18:32:32,585 [INFO] A new session has been established (session id: 214c39bb-e782-4776-87dd-b5409288356c)
2022-12-02 18:32:32,586 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:32:32,610 [INFO] Starting to receive messages from a new connection (session id: 214c39bb-e782-4776-87dd-b5409288356c)
2022-12-02 18:32:47,643 [INFO] Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2022-12-02 18:32:47,645 [INFO] Successfully retrieved access token
2022-12-02 18:32:47,648 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:32:47,653 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:32:48,117 [INFO] default.pdf file located in google drive...
2022-12-02 18:32:48,129 [INFO] Updating default.pdf file contents...
2022-12-02 18:32:49,975 [INFO] File successfully updated!
2022-12-02 18:33:52,175 [INFO] A new session has been established (session id: 91506b1c-4f71-4e44-9564-4b71902ea714)
2022-12-02 18:33:52,175 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:33:52,211 [INFO] Starting to receive messages from a new connection (session id: 91506b1c-4f71-4e44-9564-4b71902ea714)
2022-12-02 18:34:05,879 [INFO] Successfully retrieved access token
2022-12-02 18:34:05,886 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:34:05,893 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:34:06,444 [INFO] default.pdf file located in google drive...
2022-12-02 18:34:06,449 [INFO] Updating default.pdf file contents...
2022-12-02 18:34:08,483 [INFO] File successfully updated!
2022-12-02 18:34:21,867 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:34:21,868 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:34:22,366 [INFO] default.pdf file located in google drive...
2022-12-02 18:34:22,366 [INFO] Updating default.pdf file contents...
2022-12-02 18:34:24,584 [INFO] File successfully updated!
2022-12-02 18:34:45,137 [INFO] A new session has been established (session id: f3c35374-15f8-4da6-af00-461c632a8639)
2022-12-02 18:34:45,138 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:34:45,211 [INFO] Starting to receive messages from a new connection (session id: f3c35374-15f8-4da6-af00-461c632a8639)
2022-12-02 18:34:58,818 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:34:58,818 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:34:59,285 [INFO] default.pdf file located in google drive...
2022-12-02 18:34:59,289 [INFO] Updating default.pdf file contents...
2022-12-02 18:35:01,146 [INFO] File successfully updated!
2022-12-02 18:35:26,876 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 18:35:26,876 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 18:35:27,376 [INFO] default.pdf file located in google drive...
2022-12-02 18:35:27,377 [INFO] Updating default.pdf file contents...
2022-12-02 18:35:29,250 [INFO] File successfully updated!
2022-12-02 18:54:53,502 [INFO] A new session has been established (session id: 5206391d-9a20-4135-949a-d5c656358a03)
2022-12-02 18:54:53,502 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:54:53,511 [INFO] Starting to receive messages from a new connection (session id: 5206391d-9a20-4135-949a-d5c656358a03)
2022-12-02 18:54:57,990 [WARNING] Unhandled request ({'type': 'block_actions', 'block_id': '=yGhM', 'action_id': 'Fetch Tableau PDF_button_clicked'})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.action("Fetch Tableau PDF_button_clicked")
def handle_some_action(ack, body, logger):
    ack()
    logger.info(body)

2022-12-02 18:54:57,990 [INFO] Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
2022-12-02 18:55:07,521 [ERROR] Failed to run listener function (error: name 'tab' is not defined)
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 55, in message_hello
    {"type": "actions", "elements": [tab.__dict__()[0]]},
NameError: name 'tab' is not defined
2022-12-02 18:55:21,396 [ERROR] Failed to run listener function (error: name 'tab' is not defined)
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 55, in message_hello
    # {"type": "actions", "elements": [tab.__dict__()[0]]},
NameError: name 'tab' is not defined
2022-12-02 18:57:15,671 [INFO] A new session has been established (session id: 511d01aa-6d7f-451d-a84b-bb416c5790ef)
2022-12-02 18:57:15,671 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:57:15,716 [INFO] Starting to receive messages from a new connection (session id: 511d01aa-6d7f-451d-a84b-bb416c5790ef)
2022-12-02 18:57:23,597 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 70, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 36, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', None)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 55, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 18:58:22,468 [INFO] A new session has been established (session id: acbfba2b-fc1c-4b9c-9cc3-b1a02896a8ff)
2022-12-02 18:58:22,468 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:58:22,483 [INFO] Starting to receive messages from a new connection (session id: acbfba2b-fc1c-4b9c-9cc3-b1a02896a8ff)
2022-12-02 18:58:29,083 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 70, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 36, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', None)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 55, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 18:59:15,735 [INFO] A new session has been established (session id: 92784667-fadb-4535-98f7-eed59fcff061)
2022-12-02 18:59:15,735 [INFO] ⚡️ Bolt app is running!
2022-12-02 18:59:15,768 [INFO] Starting to receive messages from a new connection (session id: 92784667-fadb-4535-98f7-eed59fcff061)
2022-12-02 18:59:20,548 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 70, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 36, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', None)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 56, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 19:00:11,055 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'utils/tableau_api')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 70, in button_click_action
    pdf.upload_file(channel=body["user"]["id"])
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 32, in upload_file
    os.chdir("utils/tableau_api")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/tableau_api'
2022-12-02 19:00:21,182 [INFO] A new session has been established (session id: f2cfe0cf-2c6b-4d70-83ea-95bc1510c10c)
2022-12-02 19:00:21,182 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:00:21,281 [INFO] Starting to receive messages from a new connection (session id: f2cfe0cf-2c6b-4d70-83ea-95bc1510c10c)
2022-12-02 19:00:27,300 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 19:00:27,302 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:00:28,044 [INFO] default.pdf file located in google drive...
2022-12-02 19:00:28,050 [INFO] Updating default.pdf file contents...
2022-12-02 19:00:30,145 [INFO] File successfully updated!
2022-12-02 19:00:36,627 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 19:00:36,628 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:00:37,214 [INFO] default.pdf file located in google drive...
2022-12-02 19:00:37,214 [INFO] Updating default.pdf file contents...
2022-12-02 19:00:39,322 [INFO] File successfully updated!
2022-12-02 19:01:42,893 [INFO] A new session has been established (session id: 2343b7ce-efd1-42d2-be79-76c1c68ad384)
2022-12-02 19:01:42,893 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:01:42,914 [INFO] Starting to receive messages from a new connection (session id: 2343b7ce-efd1-42d2-be79-76c1c68ad384)
2022-12-02 19:08:23,393 [INFO] A new session has been established (session id: 768537e6-59bd-44dd-8295-ad63285780de)
2022-12-02 19:08:23,393 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:08:23,493 [INFO] Starting to receive messages from a new connection (session id: 768537e6-59bd-44dd-8295-ad63285780de)
2022-12-02 19:08:29,520 [ERROR] Failed to run listener function (error: name 'pdf3__dict__' is not defined)
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 70, in message_hello
    {"type": "actions", "elements": [pdf3__dict__()[0]]},
NameError: name 'pdf3__dict__' is not defined
2022-12-02 19:09:22,651 [INFO] A new session has been established (session id: 809baef5-7750-4417-8c7c-1dd5ba57aae6)
2022-12-02 19:09:22,652 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:09:22,689 [INFO] Starting to receive messages from a new connection (session id: 809baef5-7750-4417-8c7c-1dd5ba57aae6)
2022-12-02 19:09:33,111 [INFO] Files to be updated/uploaded: dict_keys(['default.pdf'])...
2022-12-02 19:09:33,112 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:09:33,610 [INFO] default.pdf file located in google drive...
2022-12-02 19:09:33,612 [INFO] Updating default.pdf file contents...
2022-12-02 19:09:35,727 [INFO] File successfully updated!
2022-12-02 19:14:33,958 [INFO] A new session has been established (session id: 94e45a4c-9464-4a9f-9bd8-a06341cd9f0f)
2022-12-02 19:14:33,959 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:14:33,959 [INFO] Starting to receive messages from a new connection (session id: 94e45a4c-9464-4a9f-9bd8-a06341cd9f0f)
2022-12-02 19:14:41,066 [ERROR] Failed to run listener function (error: FileUploadButton.upload_file() missing 1 required positional argument: 'manager')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"])
TypeError: FileUploadButton.upload_file() missing 1 required positional argument: 'manager'
2022-12-02 19:17:45,446 [INFO] A new session has been established (session id: 18cfa8da-ed17-47ab-8300-ebb97a276d0d)
2022-12-02 19:17:45,446 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:17:45,447 [INFO] Starting to receive messages from a new connection (session id: 18cfa8da-ed17-47ab-8300-ebb97a276d0d)
2022-12-02 19:17:50,982 [WARNING] manager is not a valid argument
2022-12-02 19:17:51,256 [ERROR] Failed to run listener function (error: FileUploadButton.upload_file() missing 1 required positional argument: 'manager')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"])
TypeError: FileUploadButton.upload_file() missing 1 required positional argument: 'manager'
2022-12-02 19:19:54,999 [INFO] A new session has been established (session id: 35e9b651-756f-44eb-babb-298f19e43093)
2022-12-02 19:19:54,999 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:19:55,008 [INFO] Starting to receive messages from a new connection (session id: 35e9b651-756f-44eb-babb-298f19e43093)
2022-12-02 19:20:04,069 [WARNING] Unhandled request ({'type': 'event_callback', 'event': {'type': 'message'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)

2022-12-02 19:20:04,070 [INFO] Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
2022-12-02 19:20:07,134 [WARNING] Unhandled request ({'type': 'event_callback', 'event': {'type': 'message'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)

2022-12-02 19:20:07,134 [INFO] Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
2022-12-02 19:20:15,546 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"], manager='Varshi Ike')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 37, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', manager)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 81, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 19:21:10,772 [WARNING] Unhandled request ({'type': 'event_callback', 'event': {'type': 'message'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)

2022-12-02 19:21:10,772 [INFO] Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
2022-12-02 19:22:10,078 [INFO] A new session has been established (session id: 151a7c47-bb51-42be-bbbe-791c4cf09c6d)
2022-12-02 19:22:10,078 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:22:10,110 [INFO] Starting to receive messages from a new connection (session id: 151a7c47-bb51-42be-bbbe-791c4cf09c6d)
2022-12-02 19:22:15,176 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"], manager='Varshi Ike')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 37, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', 'Jane Doe')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 81, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 19:23:17,656 [INFO] A new session has been established (session id: 8802476b-aa29-41ad-b8f1-910c53a2f2b9)
2022-12-02 19:23:17,657 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:23:17,670 [INFO] Starting to receive messages from a new connection (session id: 8802476b-aa29-41ad-b8f1-910c53a2f2b9)
2022-12-02 19:23:26,683 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"], manager='Varshi Ike')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 37, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', 'Jane Doe')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 81, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 19:24:03,407 [INFO] A new session has been established (session id: 9a94be32-e37e-4e44-ab53-ea07f3a12b9c)
2022-12-02 19:24:03,407 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:24:03,461 [INFO] Starting to receive messages from a new connection (session id: 9a94be32-e37e-4e44-ab53-ea07f3a12b9c)
2022-12-02 19:24:09,031 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"], manager='Varshi Ike')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 37, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', 'Jane Doe')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 81, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 19:25:47,406 [INFO] A new session has been established (session id: 1cf5ba0d-2f9c-4569-bfa9-fa4b2b7eb1e3)
2022-12-02 19:25:47,406 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:25:47,458 [INFO] Starting to receive messages from a new connection (session id: 1cf5ba0d-2f9c-4569-bfa9-fa4b2b7eb1e3)
2022-12-02 19:25:52,546 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"], manager='Varshi Ike')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 37, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', 'Jane Doe')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 82, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 19:26:13,089 [WARNING] Unhandled request ({'type': 'event_callback', 'event': {'type': 'message'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)

2022-12-02 19:26:13,090 [INFO] Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
2022-12-02 19:28:05,642 [INFO] A new session has been established (session id: 595b57f9-268d-4420-86d8-6ca0d3b18063)
2022-12-02 19:28:05,642 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:28:05,648 [INFO] Starting to receive messages from a new connection (session id: 595b57f9-268d-4420-86d8-6ca0d3b18063)
2022-12-02 19:28:10,497 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"], manager='Varshi Ike')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 37, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', 'Jane Doe')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 82, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 19:33:56,455 [INFO] A new session has been established (session id: bd158c3f-bbf8-4655-a980-f9e68246cf6b)
2022-12-02 19:33:56,455 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:33:56,557 [INFO] Starting to receive messages from a new connection (session id: bd158c3f-bbf8-4655-a980-f9e68246cf6b)
2022-12-02 19:34:03,199 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"], manager='Varshi Ike')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 37, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', 'Jane Doe')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 102, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 19:34:59,073 [INFO] A new session has been established (session id: c453f12d-349b-4949-8e0c-457b2c973d31)
2022-12-02 19:34:59,073 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:34:59,130 [INFO] Starting to receive messages from a new connection (session id: c453f12d-349b-4949-8e0c-457b2c973d31)
2022-12-02 19:35:06,154 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"], manager='Varshi Ike')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 37, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', 'Jane Doe')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 103, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 19:36:22,547 [INFO] A new session has been established (session id: 6596f6c1-005e-4c33-ae69-6c482a730854)
2022-12-02 19:36:22,547 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:36:22,578 [INFO] Starting to receive messages from a new connection (session id: 6596f6c1-005e-4c33-ae69-6c482a730854)
2022-12-02 19:36:27,705 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: '../googledrive_api/files')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"], manager='Varshi Ike')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 37, in upload_file
    generate_pdf('[Draft] NPS One Pagers Mock up', 'NPSOnePagerDIRECTROLLUP', 'Manager', 'Jane Doe')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/utils/tableau_api/pdf_creator.py", line 106, in generate_pdf
    os.chdir('../googledrive_api/files')
FileNotFoundError: [Errno 2] No such file or directory: '../googledrive_api/files'
2022-12-02 19:37:16,294 [INFO] A new session has been established (session id: b45a6fc8-49ed-4860-a6f7-fde031f621b4)
2022-12-02 19:37:16,294 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:37:16,306 [INFO] Starting to receive messages from a new connection (session id: b45a6fc8-49ed-4860-a6f7-fde031f621b4)
2022-12-02 19:37:24,910 [INFO] access_token is expired. Now: 2022-12-03 03:37:24.910698, token_expiry: 2022-12-03 03:34:04
2022-12-02 19:37:24,914 [INFO] Refreshing access_token
2022-12-02 19:37:25,246 [INFO] Files to be updated/uploaded: dict_keys(['J.pdf', 'Jane_Doe.pdf'])...
2022-12-02 19:37:25,249 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:37:25,777 [INFO] J.pdf file not located in google drive...
2022-12-02 19:37:25,784 [INFO] Uploading J.pdf file contents...
2022-12-02 19:37:27,691 [INFO] File successfully uploaded!
2022-12-02 19:37:27,691 [INFO] Jane_Doe.pdf file not located in google drive...
2022-12-02 19:37:27,692 [INFO] Uploading Jane_Doe.pdf file contents...
2022-12-02 19:37:29,347 [INFO] File successfully uploaded!
2022-12-02 19:37:29,350 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: b'files/default.pdf')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"], manager='Varshi Ike')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 45, in upload_file
    self.app.client.files_upload(channels=channel, file=self.file_path)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_sdk/web/client.py", line 2990, in files_upload
    return self.api_call("files.upload", files={"file": file}, data=kwargs)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 269, in _urllib_api_call
    f: BinaryIO = open(v.encode("utf-8", "ignore"), "rb")
FileNotFoundError: [Errno 2] No such file or directory: b'files/default.pdf'
2022-12-02 19:38:02,727 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: 'utils/tableau_api')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"], manager='Varshi Ike')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 33, in upload_file
    os.chdir("utils/tableau_api")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/tableau_api'
2022-12-02 19:38:20,266 [INFO] A new session has been established (session id: 52994f3a-185f-41d5-a3be-ccd062e31e25)
2022-12-02 19:38:20,266 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:38:20,275 [INFO] Starting to receive messages from a new connection (session id: 52994f3a-185f-41d5-a3be-ccd062e31e25)
2022-12-02 19:38:24,964 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'Jane_Doe.pdf'])...
2022-12-02 19:38:24,965 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:38:25,450 [INFO] .DS_Store file not located in google drive...
2022-12-02 19:38:25,454 [INFO] Uploading .DS_Store file contents...
2022-12-02 19:38:27,180 [INFO] File successfully uploaded!
2022-12-02 19:38:27,181 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 19:38:27,181 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 19:38:29,122 [INFO] File successfully updated!
2022-12-02 19:38:29,123 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: b'files/default.pdf')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"], manager='Varshi Ike')
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 45, in upload_file
    self.app.client.files_upload(channels=channel, file=self.file_path)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_sdk/web/client.py", line 2990, in files_upload
    return self.api_call("files.upload", files={"file": file}, data=kwargs)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 269, in _urllib_api_call
    f: BinaryIO = open(v.encode("utf-8", "ignore"), "rb")
FileNotFoundError: [Errno 2] No such file or directory: b'files/default.pdf'
2022-12-02 19:40:11,819 [INFO] A new session has been established (session id: 4c495f1a-adf9-44db-8d38-8ca28d1724fa)
2022-12-02 19:40:11,819 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:40:11,865 [INFO] Starting to receive messages from a new connection (session id: 4c495f1a-adf9-44db-8d38-8ca28d1724fa)
2022-12-02 19:40:16,245 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'Jane_Doe.pdf', 'default.pdf'])...
2022-12-02 19:40:16,246 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:40:16,812 [INFO] .DS_Store file located in google drive...
2022-12-02 19:40:16,822 [INFO] Updating .DS_Store file contents...
2022-12-02 19:40:18,865 [INFO] File successfully updated!
2022-12-02 19:40:18,865 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 19:40:18,866 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 19:40:20,806 [INFO] File successfully updated!
2022-12-02 19:40:20,806 [INFO] default.pdf file located in google drive...
2022-12-02 19:40:20,807 [INFO] Updating default.pdf file contents...
2022-12-02 19:40:22,740 [INFO] File successfully updated!
2022-12-02 19:41:12,027 [INFO] A new session has been established (session id: 545b158b-1f26-4a95-b423-7a0665591086)
2022-12-02 19:41:12,027 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:41:12,030 [INFO] Starting to receive messages from a new connection (session id: 545b158b-1f26-4a95-b423-7a0665591086)
2022-12-02 19:41:20,255 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'Jane_Doe.pdf', 'default.pdf'])...
2022-12-02 19:41:20,257 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:41:20,733 [INFO] .DS_Store file located in google drive...
2022-12-02 19:41:20,739 [INFO] Updating .DS_Store file contents...
2022-12-02 19:41:22,610 [INFO] File successfully updated!
2022-12-02 19:41:22,611 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 19:41:22,611 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 19:41:24,652 [INFO] File successfully updated!
2022-12-02 19:41:24,652 [INFO] default.pdf file located in google drive...
2022-12-02 19:41:24,653 [INFO] Updating default.pdf file contents...
2022-12-02 19:41:26,534 [INFO] File successfully updated!
2022-12-02 19:42:31,734 [INFO] A new session has been established (session id: 86c7b958-08ee-47a8-b755-ae6b1226398b)
2022-12-02 19:42:31,734 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:42:31,768 [INFO] Starting to receive messages from a new connection (session id: 86c7b958-08ee-47a8-b755-ae6b1226398b)
2022-12-02 19:42:41,164 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'Jane_Doe.pdf', 'default.pdf'])...
2022-12-02 19:42:41,166 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:42:41,637 [INFO] .DS_Store file located in google drive...
2022-12-02 19:42:41,639 [INFO] Updating .DS_Store file contents...
2022-12-02 19:42:43,585 [INFO] File successfully updated!
2022-12-02 19:42:43,585 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 19:42:43,586 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 19:42:45,463 [INFO] File successfully updated!
2022-12-02 19:42:45,463 [INFO] default.pdf file located in google drive...
2022-12-02 19:42:45,463 [INFO] Updating default.pdf file contents...
2022-12-02 19:42:47,372 [INFO] File successfully updated!
2022-12-02 19:42:58,306 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'Jane_Doe.pdf', 'default.pdf'])...
2022-12-02 19:42:58,307 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:42:58,780 [INFO] .DS_Store file located in google drive...
2022-12-02 19:42:58,780 [INFO] Updating .DS_Store file contents...
2022-12-02 19:43:00,586 [INFO] File successfully updated!
2022-12-02 19:43:00,586 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 19:43:00,586 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 19:43:02,429 [INFO] File successfully updated!
2022-12-02 19:43:02,429 [INFO] default.pdf file located in google drive...
2022-12-02 19:43:02,431 [INFO] Updating default.pdf file contents...
2022-12-02 19:43:04,361 [INFO] File successfully updated!
2022-12-02 19:43:29,395 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'Jane_Doe.pdf', 'default.pdf'])...
2022-12-02 19:43:29,397 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:43:29,888 [INFO] .DS_Store file located in google drive...
2022-12-02 19:43:29,888 [INFO] Updating .DS_Store file contents...
2022-12-02 19:43:31,692 [INFO] File successfully updated!
2022-12-02 19:43:31,692 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 19:43:31,693 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 19:43:33,576 [INFO] File successfully updated!
2022-12-02 19:43:33,576 [INFO] default.pdf file located in google drive...
2022-12-02 19:43:33,577 [INFO] Updating default.pdf file contents...
2022-12-02 19:43:35,622 [INFO] File successfully updated!
2022-12-02 19:44:17,382 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'Jane_Doe.pdf', 'default.pdf'])...
2022-12-02 19:44:17,384 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:44:17,900 [INFO] .DS_Store file located in google drive...
2022-12-02 19:44:17,901 [INFO] Updating .DS_Store file contents...
2022-12-02 19:44:20,544 [INFO] File successfully updated!
2022-12-02 19:44:20,545 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 19:44:20,545 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 19:44:22,384 [INFO] File successfully updated!
2022-12-02 19:44:22,385 [INFO] default.pdf file located in google drive...
2022-12-02 19:44:22,385 [INFO] Updating default.pdf file contents...
2022-12-02 19:44:24,213 [INFO] File successfully updated!
2022-12-02 19:50:15,604 [INFO] A new session has been established (session id: 0d55ff21-69ab-44e8-8f76-520fff855b75)
2022-12-02 19:50:15,605 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:50:15,703 [INFO] Starting to receive messages from a new connection (session id: 0d55ff21-69ab-44e8-8f76-520fff855b75)
2022-12-02 19:50:34,593 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'default.pdf'])...
2022-12-02 19:50:34,594 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:50:35,082 [INFO] .DS_Store file located in google drive...
2022-12-02 19:50:35,084 [INFO] Updating .DS_Store file contents...
2022-12-02 19:50:37,018 [INFO] File successfully updated!
2022-12-02 19:50:37,018 [INFO] default.pdf file located in google drive...
2022-12-02 19:50:37,019 [INFO] Updating default.pdf file contents...
2022-12-02 19:50:39,628 [INFO] File successfully updated!
2022-12-02 19:52:21,583 [INFO] A new session has been established (session id: 3e55e759-85ae-4d3f-bdd9-9076985ca8f8)
2022-12-02 19:52:21,583 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:52:21,608 [INFO] Starting to receive messages from a new connection (session id: 3e55e759-85ae-4d3f-bdd9-9076985ca8f8)
2022-12-02 19:52:31,951 [ERROR] Failed to run listener function (error: FileUploadButton.upload_file() missing 1 required positional argument: 'manager')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"])
TypeError: FileUploadButton.upload_file() missing 1 required positional argument: 'manager'
2022-12-02 19:53:12,429 [INFO] A new session has been established (session id: b2635e4a-6960-4329-87db-0f360873f1fd)
2022-12-02 19:53:12,429 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:53:12,466 [INFO] Starting to receive messages from a new connection (session id: b2635e4a-6960-4329-87db-0f360873f1fd)
2022-12-02 19:53:14,201 [ERROR] Failed to run listener function (error: FileUploadButton.upload_file() missing 1 required positional argument: 'manager')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 99, in button_click_action
    pdf1.upload_file(channel=body["user"]["id"])
TypeError: FileUploadButton.upload_file() missing 1 required positional argument: 'manager'
2022-12-02 19:56:00,260 [INFO] A new session has been established (session id: bce22878-54bb-4b11-b09a-6fb55dce32b3)
2022-12-02 19:56:00,261 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:56:00,308 [INFO] Starting to receive messages from a new connection (session id: bce22878-54bb-4b11-b09a-6fb55dce32b3)
2022-12-02 19:56:05,027 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'default.pdf'])...
2022-12-02 19:56:05,028 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:56:05,570 [INFO] .DS_Store file located in google drive...
2022-12-02 19:56:05,572 [INFO] Updating .DS_Store file contents...
2022-12-02 19:56:07,479 [INFO] File successfully updated!
2022-12-02 19:56:07,479 [INFO] default.pdf file located in google drive...
2022-12-02 19:56:07,479 [INFO] Updating default.pdf file contents...
2022-12-02 19:56:09,342 [INFO] File successfully updated!
2022-12-02 19:56:17,469 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'default.pdf'])...
2022-12-02 19:56:17,469 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:56:17,970 [INFO] .DS_Store file located in google drive...
2022-12-02 19:56:17,970 [INFO] Updating .DS_Store file contents...
2022-12-02 19:56:20,574 [INFO] File successfully updated!
2022-12-02 19:56:20,575 [INFO] default.pdf file located in google drive...
2022-12-02 19:56:20,575 [INFO] Updating default.pdf file contents...
2022-12-02 19:56:22,613 [INFO] File successfully updated!
2022-12-02 19:59:09,012 [INFO] A new session has been established (session id: 04fe5f64-881f-43dd-8269-fce827fff2d3)
2022-12-02 19:59:09,013 [INFO] ⚡️ Bolt app is running!
2022-12-02 19:59:09,036 [INFO] Starting to receive messages from a new connection (session id: 04fe5f64-881f-43dd-8269-fce827fff2d3)
2022-12-02 19:59:19,469 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'Jane_Doe.pdf', 'default.pdf'])...
2022-12-02 19:59:19,471 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:59:19,981 [INFO] .DS_Store file located in google drive...
2022-12-02 19:59:19,983 [INFO] Updating .DS_Store file contents...
2022-12-02 19:59:21,824 [INFO] File successfully updated!
2022-12-02 19:59:21,824 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 19:59:21,825 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 19:59:23,806 [INFO] File successfully updated!
2022-12-02 19:59:23,807 [INFO] default.pdf file located in google drive...
2022-12-02 19:59:23,807 [INFO] Updating default.pdf file contents...
2022-12-02 19:59:25,734 [INFO] File successfully updated!
2022-12-02 19:59:36,515 [INFO] Files to be updated/uploaded: dict_keys(['John_Wayne.pdf', '.DS_Store', 'Jane_Doe.pdf', 'default.pdf'])...
2022-12-02 19:59:36,517 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:59:37,007 [INFO] John_Wayne.pdf file not located in google drive...
2022-12-02 19:59:37,007 [INFO] Uploading John_Wayne.pdf file contents...
2022-12-02 19:59:38,520 [INFO] File successfully uploaded!
2022-12-02 19:59:38,520 [INFO] .DS_Store file located in google drive...
2022-12-02 19:59:38,520 [INFO] Updating .DS_Store file contents...
2022-12-02 19:59:40,398 [INFO] File successfully updated!
2022-12-02 19:59:40,398 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 19:59:40,399 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 19:59:42,313 [INFO] File successfully updated!
2022-12-02 19:59:42,313 [INFO] default.pdf file located in google drive...
2022-12-02 19:59:42,313 [INFO] Updating default.pdf file contents...
2022-12-02 19:59:44,217 [INFO] File successfully updated!
2022-12-02 19:59:54,256 [INFO] Files to be updated/uploaded: dict_keys(['Sylivia_Matthews.pdf', 'John_Wayne.pdf', '.DS_Store', 'Jane_Doe.pdf', 'default.pdf'])...
2022-12-02 19:59:54,258 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 19:59:54,767 [INFO] Sylivia_Matthews.pdf file not located in google drive...
2022-12-02 19:59:54,767 [INFO] Uploading Sylivia_Matthews.pdf file contents...
2022-12-02 19:59:56,502 [INFO] File successfully uploaded!
2022-12-02 19:59:56,503 [INFO] John_Wayne.pdf file located in google drive...
2022-12-02 19:59:56,504 [INFO] Updating John_Wayne.pdf file contents...
2022-12-02 19:59:58,372 [INFO] File successfully updated!
2022-12-02 19:59:58,373 [INFO] .DS_Store file located in google drive...
2022-12-02 19:59:58,374 [INFO] Updating .DS_Store file contents...
2022-12-02 20:00:00,196 [INFO] File successfully updated!
2022-12-02 20:00:00,196 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 20:00:00,197 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 20:00:02,090 [INFO] File successfully updated!
2022-12-02 20:00:02,090 [INFO] default.pdf file located in google drive...
2022-12-02 20:00:02,090 [INFO] Updating default.pdf file contents...
2022-12-02 20:00:04,094 [INFO] File successfully updated!
2022-12-02 20:00:04,095 [ERROR] Failed to run listener function (error: [Errno 2] No such file or directory: b'files/Sylvia_Matthews.pdf')
Traceback (most recent call last):
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 112, in button_click_action
    pdf3.upload_file(body["user"]["id"],pdf3.manager)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/buttons/file_upload_button.py", line 45, in upload_file
    self.app.client.files_upload(channels=channel, file=self.file_path)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_sdk/web/client.py", line 2990, in files_upload
    return self.api_call("files.upload", files={"file": file}, data=kwargs)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/venv/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 269, in _urllib_api_call
    f: BinaryIO = open(v.encode("utf-8", "ignore"), "rb")
FileNotFoundError: [Errno 2] No such file or directory: b'files/Sylvia_Matthews.pdf'
2022-12-02 20:02:24,417 [INFO] A new session has been established (session id: 458e4ea0-dd00-4b6e-9394-4320bc97f39b)
2022-12-02 20:02:24,418 [INFO] ⚡️ Bolt app is running!
2022-12-02 20:02:24,459 [INFO] Starting to receive messages from a new connection (session id: 458e4ea0-dd00-4b6e-9394-4320bc97f39b)
2022-12-02 20:02:32,919 [INFO] Files to be updated/uploaded: dict_keys(['John_Wayne.pdf', 'Sylvia_Matthews.pdf', '.DS_Store', 'Jane_Doe.pdf'])...
2022-12-02 20:02:32,923 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 20:02:33,454 [INFO] John_Wayne.pdf file located in google drive...
2022-12-02 20:02:33,455 [INFO] Updating John_Wayne.pdf file contents...
2022-12-02 20:02:35,530 [INFO] File successfully updated!
2022-12-02 20:02:35,530 [INFO] Sylvia_Matthews.pdf file not located in google drive...
2022-12-02 20:02:35,530 [INFO] Uploading Sylvia_Matthews.pdf file contents...
2022-12-02 20:02:37,294 [INFO] File successfully uploaded!
2022-12-02 20:02:37,295 [INFO] .DS_Store file located in google drive...
2022-12-02 20:02:37,295 [INFO] Updating .DS_Store file contents...
2022-12-02 20:02:39,411 [INFO] File successfully updated!
2022-12-02 20:02:39,411 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 20:02:39,412 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 20:02:41,329 [INFO] File successfully updated!
2022-12-02 20:03:39,796 [INFO] Files to be updated/uploaded: dict_keys(['John_Wayne.pdf', 'Sylvia_Matthews.pdf', '.DS_Store', 'Jane_Doe.pdf'])...
2022-12-02 20:03:39,796 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 20:03:40,292 [INFO] John_Wayne.pdf file located in google drive...
2022-12-02 20:03:40,292 [INFO] Updating John_Wayne.pdf file contents...
2022-12-02 20:03:42,398 [INFO] File successfully updated!
2022-12-02 20:03:42,400 [INFO] Sylvia_Matthews.pdf file located in google drive...
2022-12-02 20:03:42,401 [INFO] Updating Sylvia_Matthews.pdf file contents...
2022-12-02 20:03:44,235 [INFO] File successfully updated!
2022-12-02 20:03:44,235 [INFO] .DS_Store file located in google drive...
2022-12-02 20:03:44,236 [INFO] Updating .DS_Store file contents...
2022-12-02 20:03:46,019 [INFO] File successfully updated!
2022-12-02 20:03:46,019 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 20:03:46,020 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 20:03:48,026 [INFO] File successfully updated!
2022-12-02 20:05:18,367 [INFO] A new session has been established (session id: 3f877d56-e490-4637-8627-6ce344c77a0b)
2022-12-02 20:05:18,367 [INFO] ⚡️ Bolt app is running!
2022-12-02 20:05:18,393 [INFO] Starting to receive messages from a new connection (session id: 3f877d56-e490-4637-8627-6ce344c77a0b)
2022-12-02 20:05:30,222 [INFO] Files to be updated/uploaded: dict_keys(['John_Wayne.pdf', 'Sylvia_Matthews.pdf', '.DS_Store', 'Jane_Doe.pdf'])...
2022-12-02 20:05:30,227 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 20:05:30,720 [INFO] John_Wayne.pdf file located in google drive...
2022-12-02 20:05:30,721 [INFO] Updating John_Wayne.pdf file contents...
2022-12-02 20:05:32,589 [INFO] File successfully updated!
2022-12-02 20:05:32,589 [INFO] Sylvia_Matthews.pdf file located in google drive...
2022-12-02 20:05:32,590 [INFO] Updating Sylvia_Matthews.pdf file contents...
2022-12-02 20:05:34,547 [INFO] File successfully updated!
2022-12-02 20:05:34,548 [INFO] .DS_Store file located in google drive...
2022-12-02 20:05:34,548 [INFO] Updating .DS_Store file contents...
2022-12-02 20:05:36,408 [INFO] File successfully updated!
2022-12-02 20:05:36,409 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 20:05:36,409 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 20:05:38,541 [INFO] File successfully updated!
2022-12-02 20:06:29,438 [INFO] A new session has been established (session id: c874a52e-881b-4024-82b4-1221b7911116)
2022-12-02 20:06:29,439 [INFO] ⚡️ Bolt app is running!
2022-12-02 20:06:29,493 [INFO] Starting to receive messages from a new connection (session id: c874a52e-881b-4024-82b4-1221b7911116)
2022-12-02 20:06:38,055 [INFO] Files to be updated/uploaded: dict_keys(['John_Wayne.pdf', 'Sylvia_Matthews.pdf', '.DS_Store', 'Jane_Doe.pdf'])...
2022-12-02 20:06:38,056 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 20:06:38,613 [INFO] John_Wayne.pdf file located in google drive...
2022-12-02 20:06:38,614 [INFO] Updating John_Wayne.pdf file contents...
2022-12-02 20:06:40,445 [INFO] File successfully updated!
2022-12-02 20:06:40,445 [INFO] Sylvia_Matthews.pdf file located in google drive...
2022-12-02 20:06:40,445 [INFO] Updating Sylvia_Matthews.pdf file contents...
2022-12-02 20:06:42,348 [INFO] File successfully updated!
2022-12-02 20:06:42,348 [INFO] .DS_Store file located in google drive...
2022-12-02 20:06:42,348 [INFO] Updating .DS_Store file contents...
2022-12-02 20:06:44,194 [INFO] File successfully updated!
2022-12-02 20:06:44,194 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 20:06:44,194 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 20:06:46,064 [INFO] File successfully updated!
2022-12-02 20:08:31,968 [INFO] A new session has been established (session id: 456d54ea-44e3-4d0e-914b-9b3cc6ba7ddf)
2022-12-02 20:08:31,968 [INFO] ⚡️ Bolt app is running!
2022-12-02 20:08:31,975 [INFO] Starting to receive messages from a new connection (session id: 456d54ea-44e3-4d0e-914b-9b3cc6ba7ddf)
2022-12-02 20:08:57,897 [INFO] Files to be updated/uploaded: dict_keys(['John_Wayne.pdf', 'Sylvia_Matthews.pdf', '.DS_Store', 'Jane_Doe.pdf'])...
2022-12-02 20:08:57,903 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 20:08:58,426 [INFO] John_Wayne.pdf file located in google drive...
2022-12-02 20:08:58,428 [INFO] Updating John_Wayne.pdf file contents...
2022-12-02 20:09:00,269 [INFO] File successfully updated!
2022-12-02 20:09:00,269 [INFO] Sylvia_Matthews.pdf file located in google drive...
2022-12-02 20:09:00,269 [INFO] Updating Sylvia_Matthews.pdf file contents...
2022-12-02 20:09:02,177 [INFO] File successfully updated!
2022-12-02 20:09:02,177 [INFO] .DS_Store file located in google drive...
2022-12-02 20:09:02,178 [INFO] Updating .DS_Store file contents...
2022-12-02 20:09:04,156 [INFO] File successfully updated!
2022-12-02 20:09:04,157 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 20:09:04,157 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 20:09:06,042 [INFO] File successfully updated!
2022-12-02 20:09:21,039 [INFO] Files to be updated/uploaded: dict_keys(['John_Wayne.pdf', 'Sylvia_Matthews.pdf', '.DS_Store', 'Jane_Doe.pdf', 'Varshi_Ike.pdf'])...
2022-12-02 20:09:21,045 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 20:09:21,519 [INFO] John_Wayne.pdf file located in google drive...
2022-12-02 20:09:21,519 [INFO] Updating John_Wayne.pdf file contents...
2022-12-02 20:09:25,887 [INFO] File successfully updated!
2022-12-02 20:09:25,887 [INFO] Sylvia_Matthews.pdf file located in google drive...
2022-12-02 20:09:25,890 [INFO] Updating Sylvia_Matthews.pdf file contents...
2022-12-02 20:09:27,805 [INFO] File successfully updated!
2022-12-02 20:09:27,806 [INFO] .DS_Store file located in google drive...
2022-12-02 20:09:27,807 [INFO] Updating .DS_Store file contents...
2022-12-02 20:09:29,587 [INFO] File successfully updated!
2022-12-02 20:09:29,587 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 20:09:29,588 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 20:09:31,485 [INFO] File successfully updated!
2022-12-02 20:09:31,485 [INFO] Varshi_Ike.pdf file not located in google drive...
2022-12-02 20:09:31,485 [INFO] Uploading Varshi_Ike.pdf file contents...
2022-12-02 20:09:33,109 [INFO] File successfully uploaded!
2022-12-02 20:11:29,486 [INFO] A new session has been established (session id: 2b0491ed-bcc8-4848-baea-7561e8f57a74)
2022-12-02 20:11:29,487 [INFO] ⚡️ Bolt app is running!
2022-12-02 20:11:29,574 [INFO] Starting to receive messages from a new connection (session id: 2b0491ed-bcc8-4848-baea-7561e8f57a74)
2022-12-02 20:14:09,174 [INFO] Files to be updated/uploaded: dict_keys(['John_Wayne.pdf', '.DS_Store', 'Syliva_Matthews.pdf', 'Jane_Doe.pdf', 'Varshi_Ike.pdf'])...
2022-12-02 20:14:09,175 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-02 20:14:09,730 [INFO] John_Wayne.pdf file located in google drive...
2022-12-02 20:14:09,731 [INFO] Updating John_Wayne.pdf file contents...
2022-12-02 20:14:11,827 [INFO] File successfully updated!
2022-12-02 20:14:11,827 [INFO] .DS_Store file located in google drive...
2022-12-02 20:14:11,828 [INFO] Updating .DS_Store file contents...
2022-12-02 20:14:13,672 [INFO] File successfully updated!
2022-12-02 20:14:13,673 [INFO] Syliva_Matthews.pdf file not located in google drive...
2022-12-02 20:14:13,673 [INFO] Uploading Syliva_Matthews.pdf file contents...
2022-12-02 20:14:15,278 [INFO] File successfully uploaded!
2022-12-02 20:14:15,278 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-02 20:14:15,279 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-02 20:14:17,190 [INFO] File successfully updated!
2022-12-02 20:14:17,190 [INFO] Varshi_Ike.pdf file located in google drive...
2022-12-02 20:14:17,191 [INFO] Updating Varshi_Ike.pdf file contents...
2022-12-02 20:14:19,021 [INFO] File successfully updated!
2022-12-03 15:58:18,967 [INFO] A new session has been established (session id: 5d3acc25-0ea2-4d36-b74a-e3efc5ec2501)
2022-12-03 15:58:18,967 [INFO] ⚡️ Bolt app is running!
2022-12-03 15:58:19,018 [INFO] Starting to receive messages from a new connection (session id: 5d3acc25-0ea2-4d36-b74a-e3efc5ec2501)
2022-12-03 15:58:59,725 [INFO] access_token is expired. Now: 2022-12-03 23:58:59.725971, token_expiry: 2022-12-03 04:37:24
2022-12-03 15:58:59,726 [INFO] Refreshing access_token
2022-12-03 15:58:59,984 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'Jane_Doe.pdf'])...
2022-12-03 15:58:59,987 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-03 15:59:00,484 [INFO] .DS_Store file located in google drive...
2022-12-03 15:59:00,488 [INFO] Updating .DS_Store file contents...
2022-12-03 15:59:02,966 [INFO] File successfully updated!
2022-12-03 15:59:02,966 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-03 15:59:02,967 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-03 15:59:05,217 [INFO] File successfully updated!
2022-12-03 16:17:38,776 [INFO] A new session has been established (session id: e1e2565e-7f67-420e-a934-b58ffe9b26d9)
2022-12-03 16:17:38,776 [INFO] ⚡️ Bolt app is running!
2022-12-03 16:17:38,815 [INFO] Starting to receive messages from a new connection (session id: e1e2565e-7f67-420e-a934-b58ffe9b26d9)
2022-12-03 16:17:44,879 [WARNING] Unhandled request ({'type': 'event_callback', 'event': {'type': 'message'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)

2022-12-03 16:17:44,879 [INFO] Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
2022-12-03 16:17:47,964 [WARNING] Unhandled request ({'type': 'event_callback', 'event': {'type': 'message'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)

2022-12-03 16:17:47,964 [INFO] Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
2022-12-03 16:17:51,289 [ERROR] Failed to run listener function (error: 'dict' object has no attribute 'lower')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 63, in message_hello
    message = message.lower()
AttributeError: 'dict' object has no attribute 'lower'
2022-12-03 16:18:18,189 [ERROR] Failed to run listener function (error: 'dict' object has no attribute 'lower')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/sylvesterikpa/Desktop/Slack Bot/project_conduit/slackbot/app.py", line 63, in message_hello
    say(
AttributeError: 'dict' object has no attribute 'lower'
2022-12-03 16:18:25,133 [INFO] A new session has been established (session id: 377780fd-90b2-45d0-9381-3092fd217a22)
2022-12-03 16:18:25,133 [INFO] ⚡️ Bolt app is running!
2022-12-03 16:18:25,186 [INFO] Starting to receive messages from a new connection (session id: 377780fd-90b2-45d0-9381-3092fd217a22)
2022-12-03 16:20:00,323 [INFO] A new session has been established (session id: 343fc68d-af03-4e5b-b623-71f12320e529)
2022-12-03 16:20:00,324 [INFO] ⚡️ Bolt app is running!
2022-12-03 16:20:00,340 [INFO] Starting to receive messages from a new connection (session id: 343fc68d-af03-4e5b-b623-71f12320e529)
2022-12-03 16:21:43,237 [WARNING] Unhandled request ({'type': 'event_callback', 'event': {'type': 'message'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)

2022-12-03 16:21:43,237 [INFO] Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
2022-12-03 16:21:46,302 [WARNING] Unhandled request ({'type': 'event_callback', 'event': {'type': 'message'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)

2022-12-03 16:21:46,302 [INFO] Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
2022-12-03 16:22:49,188 [WARNING] Unhandled request ({'type': 'event_callback', 'event': {'type': 'message'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)

2022-12-03 16:22:49,188 [INFO] Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
2022-12-03 16:27:52,058 [WARNING] Unhandled request ({'type': 'event_callback', 'event': {'type': 'message'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)

2022-12-03 16:27:52,059 [INFO] Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
2022-12-03 16:34:52,829 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'Jane_Doe.pdf'])...
2022-12-03 16:34:52,833 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-03 16:34:53,309 [INFO] .DS_Store file located in google drive...
2022-12-03 16:34:53,314 [INFO] Updating .DS_Store file contents...
2022-12-03 16:34:55,698 [INFO] File successfully updated!
2022-12-03 16:34:55,698 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-03 16:34:55,699 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-03 16:34:57,855 [INFO] File successfully updated!
2022-12-03 16:43:21,050 [INFO] A new session has been established (session id: b7742004-3b7d-4bcb-aefd-199f4a94100f)
2022-12-03 16:43:21,051 [INFO] ⚡️ Bolt app is running!
2022-12-03 16:43:21,070 [INFO] Starting to receive messages from a new connection (session id: b7742004-3b7d-4bcb-aefd-199f4a94100f)
2022-12-03 16:43:46,589 [INFO] Files to be updated/uploaded: dict_keys(['.DS_Store', 'Jane_Doe.pdf'])...
2022-12-03 16:43:46,595 [INFO] file_cache is only supported with oauth2client<4.0.0
2022-12-03 16:43:47,057 [INFO] .DS_Store file located in google drive...
2022-12-03 16:43:47,062 [INFO] Updating .DS_Store file contents...
2022-12-03 16:43:49,365 [INFO] File successfully updated!
2022-12-03 16:43:49,365 [INFO] Jane_Doe.pdf file located in google drive...
2022-12-03 16:43:49,365 [INFO] Updating Jane_Doe.pdf file contents...
2022-12-03 16:43:51,721 [INFO] File successfully updated!
